

function f1g = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  F1G = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  F1G = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  f1g = importfile1("C:\Users\nicol\Desktop\Poli_Sailing\Planform\New_Anhedral_XC_optimization_BEZ_main_camber_flession\Foil_FEBE\f1g.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jan-2023 20:09:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["f1g", "VarName2", "Var3"];
opts.SelectedVariableNames = ["f1g", "VarName2"];
opts.VariableTypes = ["double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "f1g", "TrimNonNumeric", true);
opts = setvaropts(opts, "f1g", "ThousandsSeparator", ",");

% Import the data
f1g = readtable(filename, opts);

%% Convert to output type
f1g = table2array(f1g);
end